// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.78.0";
function supabaseForCaller(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function getCallerPerson(ctx) {
  const sb = supabaseForCaller(ctx);
  const { data: prof, error: profErr } = await sb.from("profiles").select("person_id").eq("user_id", ctx.getUserId()).maybeSingle();
  if (profErr) throw new Error(`profiles: ${profErr.message}`);
  if (!prof?.person_id) return { sb, person: null };
  const { data: person, error: personErr } = await sb.from("people").select("id, nome, email, papel, cargo, sub_time, local, ativo, is_admin").eq("id", prof.person_id).maybeSingle();
  if (personErr) throw new Error(`people: ${personErr.message}`);
  return { sb, person };
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna o perfil da pessoa vinculada ao usu\xE1rio autenticado (nome, cargo, papel, time).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const { person } = await getCallerPerson(ctx);
    if (!person) {
      return {
        content: [{ type: "text", text: "Usu\xE1rio autenticado mas sem perfil de pessoa vinculado." }],
        structuredContent: { user_id: ctx.getUserId(), email: ctx.getUserEmail() }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(person, null, 2) }],
      structuredContent: { person }
    };
  }
});

// src/lib/mcp/tools/list-colleagues.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_colleagues_default = defineTool2({
  name: "list_colleagues",
  title: "Listar colegas",
  description: "Lista pessoas ativas do time (nome, cargo, papel, time, localidade). Aceita filtro opcional por nome/email.",
  inputSchema: {
    search: z.string().trim().optional().describe("Filtro parcial por nome ou email."),
    limit: z.number().int().min(1).max(200).default(50).describe("M\xE1ximo de resultados (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForCaller(ctx);
    let q = sb.from("people").select("id, nome, email, cargo, papel, sub_time, local").eq("ativo", true).order("nome", { ascending: true }).limit(limit);
    if (search) q = q.or(`nome.ilike.%${search}%,email.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { count: data?.length ?? 0, people: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-vacation-balance.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_vacation_balance_default = defineTool3({
  name: "get_vacation_balance",
  title: "Consultar saldo de f\xE9rias",
  description: "Retorna o saldo de f\xE9rias da pessoa vinculada ao usu\xE1rio (ou de outra pessoa se `person_id` for informado \u2014 sujeito \xE0s pol\xEDticas de acesso).",
  inputSchema: {
    person_id: z2.string().trim().optional().describe("ID da pessoa (opcional). Padr\xE3o: o pr\xF3prio usu\xE1rio."),
    year: z2.number().int().min(2e3).max(2100).optional().describe("Ano de refer\xEAncia (opcional).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ person_id, year }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    let targetId = person_id;
    if (!targetId) {
      const { person } = await getCallerPerson(ctx);
      if (!person) {
        return { content: [{ type: "text", text: "Sem perfil vinculado." }], isError: true };
      }
      targetId = person.id;
    }
    const sb = supabaseForCaller(ctx);
    let q = sb.from("vacation_balances").select("*").eq("person_id", targetId);
    if (year) q = q.eq("year", year);
    q = q.order("year", { ascending: false });
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { person_id: targetId, balances: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-requests.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_requests_default = defineTool4({
  name: "list_my_requests",
  title: "Minhas solicita\xE7\xF5es de f\xE9rias",
  description: "Lista as solicita\xE7\xF5es de f\xE9rias do usu\xE1rio autenticado com status e datas.",
  inputSchema: {
    status: z3.string().trim().optional().describe("Filtrar por status (ex.: EM_ANALISE_GESTOR, APROVADO, REPROVADO)."),
    limit: z3.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const { person } = await getCallerPerson(ctx);
    if (!person) {
      return { content: [{ type: "text", text: "Sem perfil vinculado." }], isError: true };
    }
    const sb = supabaseForCaller(ctx);
    let q = sb.from("requests").select("*").eq("solicitante_id", person.id).order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { count: data?.length ?? 0, requests: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-absences.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_upcoming_absences_default = defineTool5({
  name: "list_upcoming_absences",
  title: "Aus\xEAncias futuras",
  description: "Lista solicita\xE7\xF5es de f\xE9rias APROVADAS que se sobrep\xF5em \xE0 janela informada (padr\xE3o: pr\xF3ximos 60 dias).",
  inputSchema: {
    start_date: z4.string().trim().optional().describe("Data inicial no formato YYYY-MM-DD (padr\xE3o: hoje)."),
    end_date: z4.string().trim().optional().describe("Data final no formato YYYY-MM-DD (padr\xE3o: hoje + 60 dias)."),
    limit: z4.number().int().min(1).max(200).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const today = /* @__PURE__ */ new Date();
    const in60 = new Date(today.getTime() + 60 * 24 * 60 * 60 * 1e3);
    const iso = (d) => d.toISOString().slice(0, 10);
    const start = start_date || iso(today);
    const end = end_date || iso(in60);
    const sb = supabaseForCaller(ctx);
    const { data, error } = await sb.from("requests").select("id, solicitante_id, data_inicio, data_fim, dias_solicitados, status, tipo").eq("status", "APROVADO").lte("data_inicio", end).gte("data_fim", start).order("data_inicio", { ascending: true }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { window: { start, end }, count: data?.length ?? 0, absences: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-recent-kudos.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_recent_kudos_default = defineTool6({
  name: "list_recent_kudos",
  title: "Kudos recentes",
  description: "Retorna os kudos (reconhecimentos) mais recentes do feed.",
  inputSchema: {
    limit: z5.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForCaller(ctx);
    const { data, error } = await sb.from("kudos").select("id, created_at, from_person_id, to_person_id, from_slack_name, to_slack_name, category, message").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { count: data?.length ?? 0, kudos: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "uhphxyhffpbnmsrlggbe";
var mcp_default = defineMcp({
  name: "ferias-sync-mcp",
  title: "F\xE9rias Sync \u2014 Gest\xE3o de pessoas",
  version: "0.1.0",
  instructions: "Ferramentas do F\xE9rias Sync para consultar dados do pr\xF3prio usu\xE1rio e do time: perfil, colegas, saldos e solicita\xE7\xF5es de f\xE9rias, aus\xEAncias futuras e kudos recentes. Todas as leituras respeitam as pol\xEDticas de acesso (RLS) do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_colleagues_default,
    get_vacation_balance_default,
    list_my_requests_default,
    list_upcoming_absences_default,
    list_recent_kudos_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
