ALTER TABLE public.requests DROP CONSTRAINT IF EXISTS requests_status_check;
ALTER TABLE public.requests ADD CONSTRAINT requests_status_check
  CHECK (status = ANY (ARRAY[
    'PENDENTE','EM_ANALISE_GESTOR','APROVADO_1NIVEL','EM_ANALISE_DIRETOR',
    'APROVADO_FINAL','REPROVADO','CANCELADO','REALIZADO','EM_ANDAMENTO',
    'RASCUNHO','INFORMACOES_ADICIONAIS'
  ]));